const datas = [
  {
    bondImage: "images/dai.png",
    bondImage2: "images/eth.jpeg.png",
    bondName: "ETH",
    payoutAssetImage: "images/eth.jpeg.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/inv.png",
    bondImage2: "images/dai.png",
    bondName: "DAI",
    payoutAssetImage: "images/dai.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/eth.jpeg.png",
    bondImage2: "images/dola.png",
    bondName: "USDT",
    payoutAssetImage: "images/dola.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/eth.jpeg.png",
    bondImage2: "images/usdc.png",
    bondName: "USDC",
    payoutAssetImage: "images/usdc.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/eth.jpeg.png",
    bondImage2: "images/fox.png",
    bondName: "WETH",
    payoutAssetImage: "images/eth.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/eth.jpeg.png",
    bondImage2: "images/inv.png",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "images/inv.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/fox.png",
    bondImage2: "images/iq.png",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "images/iq.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/eth.jpeg.png",
    bondImage2: "images/fox.png",
    bondName: "FOX",
    payoutAssetImage: "images/fox.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "images/fox.png",
    bondImage2: "images/dai.png",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "images/dai.png",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
];
export default datas;
//https://images.app.goo.gl/xyjpnGnVCZgbQpcFA
